junit:
  jupiter:
    execution:
      parallel:
        enabled: true
        mode:
          default: concurrent
          classes:
            default: concurrent


spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:latest:///
#  data:
#    redis:
#      host: 127.0.0.1
#      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect